// AssetLoader
export const ENUM_ASSET_LOADED = 'SPAR::ASSET_LOADED';

// Audio
export const ENUM_AUTOPLAY_UNLOCKED = 'SPAR::AUTOPLAY_UNLOCKED';

// Events
export const ENUM_CONNECTION_CHANGE = 'SPAR::CONNECTION_CHANGE';
export const ENUM_KEY_DOWN_CHANGE = 'SPAR::KEY_DOWN_CHANGE';
export const ENUM_KEY_UP_CHANGE = 'SPAR::KEY_UP_CHANGE';
export const ENUM_ORIENTATION_CHANGE = 'SPAR::ORIENTATION_CHANGE';
export const ENUM_VISIBILITY_CHANGE = 'SPAR::VISIBILITY_CHANGE';
export const ENUM_WINDOW_SIZE_CHANGE = 'SPAR::WINDOW_SIZE_CHANGE';

// FrameTicker
export const ENUM_FRAME_TICK = 'SPAR::FRAME_TICK';

// Sensors
export const ENUM_AMBIENT_LIGHT_CHANGE = 'SPAR::AMBIENT_LIGHT_CHANGE';
export const ENUM_GEOLOCATION_CHANGE = 'SPAR::GEOLOCATION_CHANGE';
