export const ENUM = {
  // AssetLoader
  ASSET_LOADED: 'SPAR::ASSET_LOADED',

  // Audio
  AUTOPLAY_UNLOCKED: 'SPAR::AUTOPLAY_UNLOCKED',

  // Events
  CONNECTION_CHANGE: 'SPAR::CONNECTION_CHANGE',
  KEY_DOWN_CHANGE: 'SPAR::KEY_DOWN_CHANGE',
  KEY_UP_CHANGE: 'SPAR::KEY_UP_CHANGE',
  ORIENTATION_CHANGE: 'SPAR::ORIENTATION_CHANGE',
  VISIBILITY_CHANGE: 'SPAR::VISIBILITY_CHANGE',
  WINDOW_SIZE_CHANGE: 'SPAR::WINDOW_SIZE_CHANGE',

  // FrameTicker
  FRAME_TICK: 'SPAR::FRAME_TICK',
};
