export const EVENTS = {
  // AssetLoader
  ASSETS_LOADED: 'SPAR::EVENT_ASSETS_LOADED',
  ASSET_LOADED: 'SPAR::EVENT_ASSET_LOADED',

  // Audio
  AUTOPLAY_UNLOCKED: 'SPAR::EVENT_AUTOPLAY_UNLOCKED',

  // Events
  CONNECTION_CHANGE: 'SPAR::EVENT_CONNECTION_CHANGE',
  KEY_DOWN_CHANGE: 'SPAR::EVENT_KEY_DOWN_CHANGE',
  KEY_UP_CHANGE: 'SPAR::EVENT_KEY_UP_CHANGE',
  ORIENTATION_CHANGE: 'SPAR::EVENT_ORIENTATION_CHANGE',
  VISIBILITY_CHANGE: 'SPAR::EVENT_VISIBILITY_CHANGE',
  WINDOW_SIZE_CHANGE: 'SPAR::EVENT_WINDOW_SIZE_CHANGE',

  // FrameTicker
  FRAME_TICK: 'SPAR::EVENT_FRAME_TICK',
};

export const COOKIES = {
  // Audio
  AUDIO_MUTED: 'SPAR::COOKIE_AUDIO_MUTED',
};
