// Audio
export const AUDIO_MUTED = 'SPAR::COOKIE_AUDIO_MUTED';
export const AUTOPLAY_UNLOCKED = 'SPAR::EVENT_AUTOPLAY_UNLOCKED';

// Events
export const CONNECTION_CHANGE = 'SPAR::EVENT_CONNECTION_CHANGE';
export const KEY_DOWN_CHANGE = 'SPAR::EVENT_KEY_DOWN_CHANGE';
export const KEY_UP_CHANGE = 'SPAR::EVENT_KEY_UP_CHANGE';
export const ORIENTATION_CHANGE = 'SPAR::EVENT_ORIENTATION_CHANGE';
export const VISIBILITY_CHANGE = 'SPAR::EVENT_VISIBILITY_CHANGE';
export const WINDOW_SIZE_CHANGE = 'SPAR::EVENT_WINDOW_SIZE_CHANGE';

// FrameTicker
export const FRAME_TICK = 'SPAR::EVENT_FRAME_TICK';

// Loaders
export const ASSETS_LOADED = 'SPAR::EVENT_ASSETS_LOADED';
export const ASSET_LOADED = 'SPAR::EVENT_ASSET_LOADED';
