// Cookies
// -------

// Audio
export const AUDIO_MUTED = 'SPARS::COOKIE_AUDIO_MUTED';

// Events
// ------

// Audio
export const AUTOPLAY_UNLOCKED = 'SPARS::EVENT_AUTOPLAY_UNLOCKED';

// Events
export const CONNECTION_CHANGE = 'SPARS::EVENT_CONNECTION_CHANGE';
export const KEY_DOWN_CHANGE = 'SPARS::EVENT_KEY_DOWN_CHANGE';
export const KEY_UP_CHANGE = 'SPARS::EVENT_KEY_UP_CHANGE';
export const ORIENTATION_CHANGE = 'SPARS::EVENT_ORIENTATION_CHANGE';
export const VISIBILITY_CHANGE = 'SPARS::EVENT_VISIBILITY_CHANGE';
export const WINDOW_SIZE_CHANGE = 'SPARS::EVENT_WINDOW_SIZE_CHANGE';

// FrameTicker
export const FRAME_TICK = 'SPARS::EVENT_FRAME_TICK';

// Loaders
export const ASSETS_LOADED = 'SPARS::EVENT_ASSETS_LOADED';
export const ASSET_LOADED = 'SPARS::EVENT_ASSET_LOADED';
